"""empty message

Revision ID: 02c71a66caa7
Revises: b7d4647612e8
Create Date: 2023-09-07 00:07:48.908554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c71a66caa7'
down_revision = 'b7d4647612e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    # ### end Alembic commands ###
