"""empty message

Revision ID: 675113ac9382
Revises: 02c71a66caa7
Create Date: 2023-09-07 11:40:36.543290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675113ac9382'
down_revision = '02c71a66caa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_date'))

    # ### end Alembic commands ###
